### ISSUE TITLE
Feature Request: Altering the "min Bid" or "min BIN" in the search setting

### ISSUE THREAD

**Issue by AndyHeinz** [oRastor/fut21-web-app#14]
Hi @oRastor,
as I already said, the script worls like a charm. But:

If we could enter a range (like the wait time) it'd be very nice. Right now I do this manually like every 20 minutes (min price filter: 100, then 300, then back to 0, you'll get the idea). 

This is the only way for me right now, not to get puzzled all the time. I get puzzles extensivley when sniping players. Consumables not so much. Kind of weired.

Thanks!

**Comment by Verdagen** [comment]
Truth. I also have a lot more captchas. :(
oRazor please add this option.

**Comment by yhanssens** [comment]
Are you sure looping through certain values on the min bid/price prevents captchas from showing up? Because the max bid is already randomised between 300000-800000.

**Comment by Verdagen** [comment]
> 
> 
> Are you sure looping through certain values on the min bid/price prevents captchas from showing up? Because the max bid is already randomised between 300000-800000.

Currently, I went back to the previous version and change the value MIN BID myself. Captcha doesn't appear. When I leave the new version for a few minutes I get a captcha.
