### ISSUE TITLE
A lot of buy failed

### ISSUE THREAD

**Issue by manolo75** [oRastor/fut21-web-app#16]
On PS4, since 2 days, I can't buy anything. I still get "Buy failed" and it does not seem to refresh the list correctly. Don't know if it is on sony market side or the buffer of the web-app/tool.

**Comment by oRastor** [comment]
If it requests the same bit - problem on the autobuyer side. Otherwise, it
can be a concurrent filter or EA made some new protection.

ср, 6 нояб. 2019 г. в 08:03, manolo75 <notifications@github.com>:
