### ISSUE TITLE
Working great for me!

### ISSUE THREAD

**Issue by luukvdaa** [oRastor/fut21-web-app#17]
Thank you, oRastor!!

do people want to help each other to find best filters to make the most coins as possible?
add my on snap: luukvanderaa

ps im dutch

**Comment by Mitchell46** [comment]
And what is the most coins  as passible? what do you earn a day?

**Comment by luukvdaa** [comment]
Send me a message on snap

**Comment by Mitchell46** [comment]
Heb geen snap

**Comment by KhairulAzmi21** [comment]
what is snap ya?

**Comment by Mitchell46** [comment]
Snapchat I think

**Comment by totti240282** [comment]
but how i used this script ?

Via Chrome ?
