### ISSUE TITLE
Continuesly Ban/Transferblock

### ISSUE THREAD

**Issue by Redaa91** [oRastor/fut21-web-app#18]
Dear code/programmer.
Everytime whenever i have a reasonable filter and i make some good coins i get a transferblock after just a few minutes of searching with the autobuyer, quite frustrating.
This transferban can take up to 24 hours or even 2/3 days.
Whenever it is very hard to make some coins or find a good snipingfilter i never get this transferban.
But whenever i make like 10K every 15 minutes i immediately get transferbanned.

Please fix this, otherwise this autobuyer becomes pretty useless.

**Comment by turbopinguin** [comment]
What kind of filters do you use then? since in the last few days I can't realy find something good. Also i have sometimes the same issue, Can you get permanent banned for that?

**Comment by Mitchell46** [comment]
Do you solve the puzzle, becouse I never had a ban. The puzzle pops up after a few minutes when I start it.

**Comment by Redaa91** [comment]
> Do you solve the puzzle, becouse I never had a ban. The puzzle pops up after a few minutes when I start it.

Im not talking about permannt tranferban, i am talking about termporary transfermarktban/block.
Whenever you start to make good coins when there is finaly a good filter you get transferblocked immediately. 
''Too many auctions has been taken, this function has been temporarily blocked'''blabla..
The autobuyer just seems useless whenever you start to make some serious coins. You get transferblocked immediately.

**Comment by Mitchell46** [comment]
Oooh lol then u have a good filter.. never had that ban🤣

**Comment by Redaa91** [comment]
gold defenders last week, gold bundesliga, cam cm, cdm cm etc. Im sure you had this block. A red message right at the right top.
Youre unable to to or buy then for 10 mins sometimes 30 minutes sometimes 6 hours.

**Comment by Mitchell46** [comment]
Any good filters now? 😋
