### ISSUE TITLE
Statistics & search not working after update from EA

### ISSUE THREAD

**Issue by Mitchell46** [oRastor/fut21-web-app#19]
Hi @oRastor,

After a update the statistics, searches, sold items, unsold items, coins etc isn't working when i'm searching for items. 

I'm still able to buy players or consumables.

**Comment by turbopinguin** [comment]
Yeah same issue right here. I think he will update it soon, give him some time. it works so its okay for me

**Comment by Redaa91** [comment]
I got permanently banned now because of this, i just had a feeling last night i was gonna get banned because of this. Next day banned. 2 months no problem. 1 change and i get banned permanently.

**Comment by Redaa91** [comment]
@oRastor please fix this mate i lost millions of coins now.

**Comment by miko8x** [comment]
Same issue here

**Comment by Mitchell46** [comment]
Because of the update banned?

**Comment by Redaa91** [comment]
Yes I have now 2 accounts permanently banned because of ''modified clients, botting''
Since yesterday search and stastitics not working anymore and i already had a weird feeling i should not continue autobuying.
But the same night i kept autobuying and now i am banned for ever.
He needs to fix this as soon as possible otherwise everybody who use this autobuyer will be banned forever.

**Comment by oRastor** [comment]
I still haven't an account with an active transfer market for test.

**Comment by Redaa91** [comment]
> I still haven't an account with an active transfer market for test.

So after 2 months you still not able to acces the transfermarket ? Really ?
How do you code and script this autobuyer then ?

Meanwhile people are now getting permanently banned all over the place and you are asking for donations to support you and your family ?

Really brother ?

**Comment by Redaa91** [comment]
> Because of the update banned?

Ben je trouwens Nederlands ?
Ik zou niet meer gaan autobuyen als ik jou was. 
Heb net weer iemand gesproken die gebanned is.
Mensen worden nu achter elkaar gebanned, en deze kerel wil het niet fixen.

**Comment by Mitchell46** [comment]
@Redaa91 ja man, heb het vandaag wel gedaan. Maar ben inmiddels gestopt. Ben benieuwd of ik nou ook een ban krijg. Anders verkoop ik het spel gelijk.

**Comment by oRastor** [comment]
> > I still haven't an account with an active transfer market for test.
> 
> So after 2 months you still not able to acces the transfermarket ? Really ?
> How do you code and script this autobuyer then ?
> 
> Meanwhile people are now getting permanently banned all over the place and you are asking for donations to support you and your family ?
> 
> Really brother ?

lol, because I don't play FIFA. It has be written for FIFA 19 and I played and used it successfully last year. And buy it (FIFA 20) just for trying to support this software. I played more than 30 games and still not got access to transfer. I have not time to play FIFA 20 and support this software.

I never asked for donations! What are you talking about?

**Comment by vitorkrau** [comment]
guys, the problem with statistics is on line 57 of the autobuyer itself. 
just change this line window.futStatistics.coins = services.User.getUser()._coins.amount.toLocaleString();
to window.futStatistics.coins = services.User.getUser().coins.amount.toLocaleString();
without the underscore before coins..

@oRastor I fixed for my self and I think u can understand what I wrote but I can do a PR if you want.

**Comment by miko8x** [comment]
Guys thanks for everyone looking to into this.

@oRastor never asked for donation, it was I who suggested to donate in order to make this fully featured

**Comment by oRastor** [comment]
> guys, the problem with statistics is on line 57 of the autobuyer itself.
> just change this line window.futStatistics.coins = services.User.getUser()._coins.amount.toLocaleString();
> to window.futStatistics.coins = services.User.getUser().coins.amount.toLocaleString();
> without the underscore before coins..
> 
> @oRastor I fixed for my self and I think u can understand what I wrote but I can do a PR if you want.

Please make PR, because I cannot test it!

**Comment by Redaa91** [comment]
> > > I still haven't an account with an active transfer market for test.
> > 
> > 
> > So after 2 months you still not able to acces the transfermarket ? Really ?
> > How do you code and script this autobuyer then ?
> > Meanwhile people are now getting permanently banned all over the place and you are asking for donations to support you and your family ?
> > Really brother ?
> 
> lol, because I don't play FIFA. It has be written for FIFA 19 and I played and used it successfully last year. And buy it (FIFA 20) just for trying to support this software. I played more than 30 games and still not got access to transfer. I have not time to play FIFA 20 and support this software.
> 
> I never asked for donations! What are you talking about?

So you calling me a liar now ?
Yesterday when EA updated the webapp and your autobuyer started to acting strange i gone do dashboard to remove the autobuyer and re-instal it.
When i got into dashboard a message screen popped up oRastor is asking for donations to support his projects and his family etc.

So again you are calling me a liar now ?

https://www.5mmo.com/fifa-20-account/

Here you can buy accounts with webapp transferacces.
45 euro, dont you think its worth the money if you wanna invest in your project and want to make this as succesfull as possible so people are going to start apreciate your work and THEN donate to you ?

People from all over the world are now waiting for you to fix this, you cannot let these people down in my opinion.

**Comment by Redaa91** [comment]
> @Redaa91 ja man, heb het vandaag wel gedaan. Maar ben inmiddels gestopt. Ben benieuwd of ik nou ook een ban krijg. Anders verkoop ik het spel gelijk.

Mooi, en waarschuw gelijk iedereen die deze autobuyer gebruikt.
Ik heb inmiddels meer mensen gesproken en 5 mensen hebben een ban (5 more people banned).
GEBRUIK DEZE AUTOBUYER NIET !!

Zolang hij niet van zijn luie reet af wil komen en dit niet wil fixen maar wel om donaties blijft vragen moet je alles doen om mensen ervan te weerhouden deze autobuyer te gebruiken.

**Comment by miko8x** [comment]
@Redaa91 
You’re being rude now, this is an open source project and he made it voluntarily 
He don’t owe you nothing

You are more than welcome to pay for other services

**Comment by Redaa91** [comment]
> @Redaa91
> You’re being rude now, this is an open source project and he made it voluntarily
> He don’t owe you nothing
> 
> You are more than welcome to pay for other services

Well then dont ask for donations if this is a broken project and people are getting into trouble because of it. Plain and simple right ?.

**Comment by Redaa91** [comment]
> guys, the problem with statistics is on line 57 of the autobuyer itself.
> just change this line window.futStatistics.coins = services.User.getUser()._coins.amount.toLocaleString();
> to window.futStatistics.coins = services.User.getUser().coins.amount.toLocaleString();
> without the underscore before coins..
> 
> @oRastor I fixed for my self and I think u can understand what I wrote but I can do a PR if you want.

It would be great if you could help some of us Dutchies out because most of us here dont know how to code and such.

**Comment by miko8x** [comment]
He didn’t ask for anything and he shared the code with us

Personally, I think that long term support in this project should cost time and time = money

So we can all donate together to show our appreciation

**Comment by Redaa91** [comment]
> He didn’t ask for anything and he shared the code with us
> 
> Personally, I think that long term support in this project should cost time and time = money
> 
> So we can all donate together to show our appreciation

Again, yesterday evening when i wanted to reinstal the autobuyer in dashboard: Click tampermonkey logo right top --> dashboard i get into dashboard and a screen popped up asking for donations.
I wouldnt mind donate a few euros but if hes not even willing to fix this why would i.

**Comment by miko8x** [comment]
Yes man but that’s because EA rolled a new patch and he doesn’t have an account to test it.
Let’s get him one, I don’t mind to pay for it

**Comment by vitorkrau** [comment]
I made a pull request fixing the problem. Just wait for rastor to accept and you can download the new update.

**Comment by miko8x** [comment]
@vitorkrau  thanks man, you’re the best

**Comment by oRastor** [comment]
merged pull request

**Comment by oRastor** [comment]
> So you calling me a liar now ?
> Yesterday when EA updated the webapp and your autobuyer started to acting strange i gone do dashboard to remove the autobuyer and re-instal it.
> When i got into dashboard a message screen popped up oRastor is asking for donations to support his projects and his family etc.
> 
> So again you are calling me a liar now ?
> 
> https://www.5mmo.com/fifa-20-account/
> 
> Here you can buy accounts with webapp transferacces.
> 45 euro, dont you think its worth the money if you wanna invest in your project and want to make this as succesfull as possible so people are going to start apreciate your work and THEN donate to you ?
> 
> People from all over the world are now waiting for you to fix this, you cannot let these people down in my opinion.

Man, don't talk stupid things. You can view all source code of this application, please find something like dialog for donations.

Maybe it was generated by your browser's plugin.

**Comment by oRastor** [comment]
Let's check that all works!
Stop spamming!

**Comment by vitorkrau** [comment]
The donations popup is from tampermonkey not from the autobuyer itself.

**Comment by miko8x** [comment]
Fine on my end, thanks guys!

**Comment by manolo75** [comment]
Not working well for me. No bars moving for search and statistics. No active transfers etc... 
So no counters, but it looks like the rest of the autobuyer is working well.
Thank you for your work and sharing it with us

**Comment by manolo75** [comment]
Me again. After a cache clean on my browser, bars and counters working back. Cheers.

**Comment by Mitchell46** [comment]
thanks @manolo75, gonna give it a try!

**Comment by Mitchell46** [comment]
not working for me cleaning my cache.

**Comment by Mitchell46** [comment]
> guys, the problem with statistics is on line 57 of the autobuyer itself.
> just change this line window.futStatistics.coins = services.User.getUser()._coins.amount.toLocaleString();
> to window.futStatistics.coins = services.User.getUser().coins.amount.toLocaleString();
> without the underscore before coins..
> 
> @oRastor I fixed for my self and I think u can understand what I wrote but I can do a PR if you want.

Deleting the underscore works perfect. Thanks @vitorkrau!

**Comment by Redaa91** [comment]
> > guys, the problem with statistics is on line 57 of the autobuyer itself.
> > just change this line window.futStatistics.coins = services.User.getUser()._coins.amount.toLocaleString();
> > to window.futStatistics.coins = services.User.getUser().coins.amount.toLocaleString();
> > without the underscore before coins..
> > @oRastor I fixed for my self and I think u can understand what I wrote but I can do a PR if you want.
> 
> Deleting the underscore works perfect. Thanks @vitorkrau!

Zou je mij kunnen helpen ? Dat ding vind echt helemaal niks meer sinds die fix...

**Comment by Mitchell46** [comment]
Ik zoek vaker naar positie kaartjes en nu naar La liga spelers zoeken met hogere rating. Die zijn nu bijna 40% duurder door die flashback kaart van David Vila

**Comment by Redaa91** [comment]
> Ik zoek vaker naar positie kaartjes en nu naar La liga spelers zoeken met hogere rating. Die zijn nu bijna 40% duurder door die flashback kaart van David Vila

Zou je wat specifieker kunnen zijn ?
Positiekaartjes die doen het altijd wel redelijk, de ene keer wat beter dan de andere keer.
Maar buiten dat is er helemaal niks, iedereen zegt dat de winsten niet opschieten.
