### ISSUE TITLE
no cards on autobuyer, but on transfermarkt they are.

### ISSUE THREAD

**Issue by Redaa91** [oRastor/fut21-web-app#22]
I am searching for wesley hoedt, he is 5000K now.
When i go back to transfermarket there are cards from him 400 or 500 coins all the time so i can now make potential sick profit however the autobuyer cannot find 1....why not ?
When i go back to transfermarkt and i do max prize 1000 every minute maybe 30/40 cards pop up but none on the autobuyer.

Also i checked on ps4, same thing many cards pop up. 
Someone knows whats going on ?

**Comment by Mitchell46** [comment]
I don't have that problem now. Can find many Hoedt cards.
