### ISSUE TITLE
Not buying eligible cards?

### ISSUE THREAD

**Issue by mrtrim** [oRastor/fut21-web-app#23]
Hi, love the script, have been using for a couple of weeks now and is very effective, and incredibly easy to use.

Quick one - last two or three days (not sure when it started) after a good few hours of running the script and going thru the few verification screens when asked, it seems to be getting to a stage where it doesn't buy anything, despite everything fitting criteria? 

So I'll continue running the same criteria (in this instance it was Special cards under a certain amount, reselling 200 more) and it worked for hours, (bar one or two 'No Robots' checks) and then it'll only return 'buy failed' results for what seemed to be eligible entries. This continued until overnight too, I've tried binning cookies etc but literally nothing changed until the morning after?

Hope this helps, seems like a time triggered security check from server, but not sure why it would have reset overnight?

**Comment by vitorkrau** [comment]
Sometimes when you buy and sell a lot of cards, EA sports block you from transfer market for a couple of hours. Maybe is that.

**Comment by mrtrim** [comment]
I did wonder if that might be it, everything else works fine, it's literally just buying players through the script that doesn't seem to work. I'll try and buy a player manually and see if that is any different, thanks for the reply

**Comment by mrtrim** [comment]
I think you're right, I've just tried a couple of BIN situations on the same type of players, and both transactions just seem to 'null' out, no error, no warning, no transaction. 

Thanks for answering vitorkrau, do you know it this would contribute to a future ban, or if there is a way to reset it? 

Thank you

**Comment by mrtrim** [comment]
Just tried a normal bid, and I get the 'too many transactions' message, makes sense now, thank you friend, is this something that could have a scripted alert? Thanks again

**Comment by vitorkrau** [comment]
Probably could lead to a ban. I don't have time right now to see if it's possible to alert the user about that lock if it's that what u meant. One thing I always do is set a application called PC Sleep to lock me out of my Windows account after a while.

**Comment by mrtrim** [comment]
Ok thanks, really appreciate the help
