### ISSUE TITLE
witch exenties must used for the autobuyer

### ISSUE THREAD

**Issue by leonpellegrom** [oRastor/fut21-web-app#28]
hello i from holland and i wont to used autobuyer i got 3 links but when i klik on RAW i see no INSTALL i must extensies in chrome downloden but where i find them en witch i have to 
sorry for my bad englisch

**Comment by melleFifaPro** [comment]
Hey leon,
Ik wil het je wel vertellen in ruil voor alle 3 die links want ik heb al wel autobuyer maar nog geen snipefilters. DUs drop je instagram en we dm en verder en ik help je met het instaleren van de auto buyer.
groetjes Melle
