### ISSUE TITLE
I just dont understand this, developers/coders answer please ?

### ISSUE THREAD

**Issue by Redaa91** [oRastor/fut21-web-app#29]
Developers ?
https://imgur.com/qHUJghM
Sometimes 20/30 failed in a row, even more.
This filter is Lyon from marquee matchups sbs.
Whenever this SBC came out from the beginning of FIFA i made tons of coins on evening.
Last 2/3 months the autobuyer does NOT buy anything anymore whenever marquee matchups sbc comes ouot and i use the filter?
Something must have happened in order for the autobuyer not working anymore.

You cant have 5/6/7/8/9/0 Buy Failed in a row otherwise you will get transferblock.
So i can just let it run, but i putt myself to risk getting transferbanned and eventually permanently banned.
So something must have happened in order for the autobuyer not buying anything anymore whenever this SBC comes out with very good profitable filteres.

please clarify some one...

**Comment by KhairulAzmi21** [comment]
you think you the only one using that filter ? of course you will get failed buy .
