### ISSUE TITLE
Fifa 21

### ISSUE THREAD

**Issue by marcelino69** [oRastor/fut21-web-app#36]
Hi Orest,

First of all, I really appreciatie your work! I know some people have been mad on you in the past. But your autobuyer has never let me down! I was wondering... Will this autobuyer be able to run on the FIFA 21 web app? If not, would you pleasr convert it to the fifa 21 web app? It will help me out a lot! Thanks!

**Comment by oRastor** [comment]
I think that it will work for FUT 21. Wait until it comes out...

**Comment by marcelino69** [comment]
Wow! Thanks for the quick respond! I’ll be in touch... 😉

**Comment by KhairulAzmi21** [comment]
Hopefully it will still work :D .

**Comment by marcelino69** [comment]
It works! You just have to adjust the URL in the code to: https://www.ea.com/en-gb/fifa/ultimate-team/web-app/

Good luck sniping!

**Comment by Zotteros99** [comment]
Where exactly did you paste it without errors?

**Comment by aniuspms** [comment]
not working for me.

**Comment by kkentam** [comment]
not working too. Even I replace those var name

**Comment by TiebeVercoutter** [comment]
Hi everybody I have a version on my profile that works for fifa21 I changed the fifa20 code from somebody else a few months ago but the guy just stole it from oRastor I think. Feel free to look at some of my changes and use them.

**Comment by oRastor** [comment]
Updated URL for the new version. Can someone test it? I have not access to transfers...

**Comment by manolo75** [comment]
Works like a charm on https://www.futbin.com/21/player/1104/florian-thauvin

Le mer. 30 sept. 2020 à 22:53, Orest Budzhak <notifications@github.com> a
écrit :

**Comment by oRastor** [comment]
> Hi everybody I have a version on my profile that works for fifa21 I changed the fifa20 code from somebody else a few months ago but the guy just stole it from oRastor I think. Feel free to look at some of my changes and use them.

lol, its a copy of code from this repository. But from the beginning, my repo was a fork with a lot of UI changes with a progress bar and counters. But forked repo was deleted and my repo lost fork status. Then I made some changes to support FUT 20 engine changes.

**Comment by TiebeVercoutter** [comment]
Well yes I said somebody copied it from you and i just made some changes like some basic profit calculator and giving you a warning + stopping the bot when a captcha is required 

I never claimed I didn’t copy it i just saw some people having trouble so i tried to help

There are many people on yt + insta trying to sell this open source software for money...

**Comment by oRastor** [comment]
> Well yes I said somebody copied it from you and i just made some changes like some basic profit calculator and giving you a warning + stopping the bot when a captcha is required
> 
> I never claimed I didn’t copy it i just saw some people having trouble so i tried to help
> 
> There are many people on yt + insta trying to sell this open source software for money...

Feature with captcha is cool! Can you make PR to this repo?
I don't play FUT for more than 2 years, but a lot of people use this tool from the current repo. I can support sometimes this repo if people use this tool.

**Comment by cittamaniak1990** [comment]
to start he searches 1 time,

after that, that bar lasts a very long time and looks no further
