### ISSUE TITLE
pinEvents & Lock Risks

### ISSUE THREAD

**Issue by d235** [oRastor/fut21-web-app#4]
hi,
the autobuyer don't create calls like 

https://pin-river.data.ea.com/pinEvents

could this lead to locks and bans?

Is this dangerous?

**Comment by boefiee** [comment]
The autobuyer is not working properly at all.
Whenever i am searching on a diffrent account with the ps4 for the same player/item, loads of cards pop up.
Nothing pops up with the autobuyer, maybe 1 in 5/10 minutes...

Also many fails and cards with same ID.
Last year it worked great and i really apreciate the work and effort, but this year it seems a little rusty and not working normaly.
Hope someone can make some changes and updates and let us enjoy this great autobuyer once again.

Thanks !

**Comment by oRastor** [comment]
On which requests there are not pinEvents?

**Comment by d235** [comment]
As soon i go to the autobuyer tab- no more pinEvents - in real webapp there is between every single search a PinEvent-Call

**Comment by totti240282** [comment]
pinEvents is problem ?
