### ISSUE TITLE
Missing menu and tutorial

### ISSUE THREAD

**Issue by Mitiaro** [oRastor/fut21-web-app#41]
Hi i am trying to use the scripts but the menu is missing?
Can someone explain how to install and use the bot?

**Comment by ab-user1** [comment]
Yea I see owner has changed it. Impossible to install it now.
Also check my new post/issue.
Maybe it's better for anyone not to install this anymore till the owner and developer completely makes sure this script is safe to use.

**Comment by oRastor** [comment]
> Yea I see owner has changed it. Impossible to install it now.
> Also check my new post/issue.
> Maybe it's better for anyone not to install this anymore till the owner and developer completely makes sure this script is safe to use.

It was tested before push. You need to use only one new script, and disable old 2
