### ISSUE TITLE
autobuyer user / menu ?

### ISSUE THREAD

**Issue by ab-user1** [oRastor/fut21-web-app#43]
Dear developer,

Autobuyer menu / user has been removed and the autobuyer seem to be working less well.
Why did you remove autobuyer menu and user ?
What are we suppose to install now for a good working autobuyer ?

Thanks in advance.

**Comment by oRastor** [comment]
It was merged into one file

**Comment by oRastor** [comment]
fut21-autobuyer.user.js

**Comment by ronbeton-gif** [comment]
what should we change now? wat moeten we nu eraan veranderen

**Comment by ronbeton-gif** [comment]
whats now the official link? @oRastor

**Comment by TiebeVercoutter** [comment]
You just have to remove the 2 old files and import the new file which is just the 2 old files combined

**Comment by aniuspms** [comment]
search thing now not working good, I made 7-15, and bot searching every 5 sec, or less.
Also a lot of warning now, tbh before was better without changes which you made.

**Comment by oRastor** [comment]
> You just have to remove the 2 old files and import the new file which is just the 2 old files combined

https://github.com/oRastor/fut21-web-app/blob/master/fut21-autobuyer.user.js

**Comment by oRastor** [comment]
> search thing now not working good, I made 7-15, and bot searching every 5 sec, or less.
> Also a lot of warning now, tbh before was better without changes which you made.

Please check that only one script works for you now

**Comment by ab-user1** [comment]
@oRastor 

Hey Orest, please check my previous post concerning the webapp coding and EA trying to catch chrome bots/scripts.

**Comment by aniuspms** [comment]
> > search thing now not working good, I made 7-15, and bot searching every 5 sec, or less.
> > Also a lot of warning now, tbh before was better without changes which you made.
> 
> Please check that only one script works for you now

cheers bro, what search time do you recommended?

**Comment by TiebeVercoutter** [comment]
> search thing now not working good, I made 7-15, and bot searching every 5 sec, or less.
> Also a lot of warning now, tbh before was better without changes which you made.

Yes i made some changes that fixed the wait time issue as you can see the wait time is now correct between the interval.
![image](https://user-images.githubusercontent.com/54238250/95012954-1cbf4180-063d-11eb-9190-a348a610c642.png)

**Comment by aniuspms** [comment]
> > search thing now not working good, I made 7-15, and bot searching every 5 sec, or less.
> > Also a lot of warning now, tbh before was better without changes which you made.
> 
> Yes i made some changes that fixed the wait time issue as you can see the wait time is now correct between the interval.
> ![image](https://user-images.githubusercontent.com/54238250/95012954-1cbf4180-063d-11eb-9190-a348a610c642.png)

yeah working now, what search time do you recommended? mean safe way.
