### ISSUE TITLE
Anyone can help me out?

### ISSUE THREAD

**Issue by BandietosGaming** [oRastor/fut21-web-app#44]
Hi! 

First of all thanks to all the developers who make this app working and free! 
DONT forget that guys, they do a lot of work. 

Since this morning i get a search fail from the web app. I use the UK webapp and never get problems (last year and this year).

The message is as followed; 

Sorry an error has occurred while trying to complete your search. Please try again in a moment. 

This message show up when i want to search on the normale transfermarket on the web app. In the autobuyer, i can buy players aswell.

Anyone experience with it and could help me?

Kind Regards,

Niels

**Comment by RyanNL1994** [comment]
I have the same problem I googled it and apparently it's a soft ban. It should be over in like 12-24 hours according to the forums I have read. The problem may lie with the fast snipping you use with the bot so EA will recognize you are not a human who is trading is my guess. I haven't had this in fifa 20 anyways I think you should be able to search for players again in like 12-24 hours
