### ISSUE TITLE
Only short-time results

### ISSUE THREAD

**Issue by lindgr0n** [oRastor/fut21-web-app#46]
Hi guys, FUT21 buyer is active. Installation and setup worked perfectly fine, but results are limited to the first minute or so. Anyone with the same issue? 

My initial guess is that the search isn't refreshed at all. Is there a possibility to let the min bid go up 150 per search (until 650) and then back down? That's enough for the webapp to refresh continuously when done by hand, so must be implementable I guess. I tried adding it in Python but can't get it fully covered. 

Thanks for your hard work.

**Comment by TiebeVercoutter** [comment]
New players still come up, sold players may need some time to not show up anymore but this only takes a minute or 2 at max. 

This is only a visual bug and doesn’t affect the functionality of the bot since the max buy price are randomised each search.

Since you are familiar with python it shouldn’t be a big step to JavaScript and you could just make adjustments to the JavaScript file yourself instead of using Python😀

**Comment by oRastor** [comment]
> Hi guys, FUT21 buyer is active. Installation and setup worked perfectly fine, but results are limited to the first minute or so. Anyone with the same issue?
> 
> My initial guess is that the search isn't refreshed at all. Is there a possibility to let the min bid go up 150 per search (until 650) and then back down? That's enough for the webapp to refresh continuously when done by hand, so must be implementable I guess. I tried adding it in Python but can't get it fully covered.
> 
> Thanks for your hard work.

You must specify a more harder filter to get fewer items. We can make only one search request for "wait time". If we want to make a virtual scroll and load more pages - wee need makes more than one request. The chance of getting banned increases. So, load more than one page is not possible with autobuyer.

**Comment by lindgr0n** [comment]
Clear, thanks for the reply guys. 

@oRastor I don't mean loading more pages, just hard forcing a new refresh in results. But as Tiebe says the max buy price is randomised, that's roughly what I meant. Thx!
