### ISSUE TITLE
Short results

### ISSUE THREAD

**Issue by basgrootveld** [oRastor/fut21-web-app#47]
When I turn the bot on I get a warning fast and then the bot turns off, this happend after around 15-20 mins. Is there a way to have less warnings and make more coins afk?

**Comment by TiebeVercoutter** [comment]
A warning is called when a search request fails indicating that there is something wrong. I implemented this feature to notify myself when captha verification is required by ea. Continuing searching when verification is required is wasting time and could lead to a quicker ban. After these warnings do you have do a quick puzzle after refreshing the web app? If not it might be an issue with your connection.

To get less verifications buy less players in a short time and increase waiting times between searches

**Comment by RyanNL1994** [comment]
> A warning is called when a search request fails indicating that there is something wrong. I implemented this feature to notify myself when captha verification is required by ea. Continuing searching when verification is required is wasting time and could lead to a quicker ban. After these warnings do you have do a quick puzzle after refreshing the web app? If not it might be an issue with your connection.
> 
> To get less verifications buy less players in a short time and increase waiting times between searches

Do you have a good/ideal wait time for the autobuyer?
I got my second temp. Ban today on the webapp so I cant search players anymore did not had this problem with fifa 20 autobuyer
