### ISSUE TITLE
WARNING issue

### ISSUE THREAD

**Issue by maro-cell** [oRastor/fut21-web-app#48]
I get alot of Warning and it stops searching, have solution for this? Thank you.

**Comment by TiebeVercoutter** [comment]
This is an implemented safety feature but it could use an update to describe it better.

Are you buying lots of players at the same time? When a warning appears and it stops the bot that likely means captcha verification is required or there went something wrong on the server side.

The bot is stopped so you don’t wast time searching when you have to verify

**Comment by ronbeton-gif** [comment]
what is now the official link of the autobuyer to install him?

**Comment by oRastor** [comment]
> what is now the official link of the autobuyer to install him?

https://github.com/oRastor/fut21-web-app/raw/master/fut21-autobuyer.user.js
