### ISSUE TITLE
Buy Failed

### ISSUE THREAD

**Issue by mrfifa21** [oRastor/fut21-web-app#49]
Hi, 

It keeps giving the notification "Buy Failed" it doesnt buy any players even if the remaining time 1 minute. Please help!

**Comment by TiebeVercoutter** [comment]
Temporary market ban

**Comment by oRastor** [comment]
"Buy Failed" occurs when:
- you have not money to by an item
- item already not active (it was bought by another user)
- temporary ban
- other reason

"remaining time 1 minute" is not a logical reason...

**Comment by Steeffeh** [comment]
> 
> 
> Hi,
> 
> It keeps giving the notification "Buy Failed" it doesnt buy any players even if the remaining time 1 minute. Please help!

When I got this error this is what I do..

I check if i can BID on a random player(manually). If you get a message Too many actions................. Then you know you got a temporary ban for bidding and buying on the webapp.

It's a tip :)

**Comment by Mitchell46** [comment]
> Hi,
> 
> It keeps giving the notification "Buy Failed" it doesnt buy any players even if the remaining time 1 minute. Please help!

I think allot of other autobouyers are on the same item.
