### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by boyan1991** [oRastor/fut21-web-app#53]
it´s impossible to buy players, he only search for player but doesn´t buy it.

**Comment by oRastor** [comment]
Very informative issue... Maybe you can show a screenshot?

**Comment by manolo75** [comment]
I guess it is because you did not enter any sell price. Is there a way to buy players without reselling them instantly ?

**Comment by oRastor** [comment]
> I guess it is because you did not enter any sell price.
No, he said that autobuyer doesn't buy items.

>Is there a way to buy players without reselling them instantly ?
Leave blank sell price
