### ISSUE TITLE
Autobuyer not appearing

### ISSUE THREAD

**Issue by ruubmarges** [oRastor/fut21-web-app#60]
Hi There,

Autobuyer isn't appearing anymore on the web app. EA has put out a new update, but I dont think that has something to do with it.. Any help? :) Much appreciated.

**Comment by Batita77** [comment]
I have the same problem too. Help needed on what to do. Many thanks

**Comment by oRastor** [comment]
fixed in new version

**Comment by KhairulAzmi21** [comment]
> fixed in new version

bro you still playing fut ?

**Comment by ruubmarges** [comment]
@oRastor Is there a link to the new version? Thanks :)

**Comment by oRastor** [comment]
> @oRastor Is there a link to the new version? Thanks :)

https://github.com/oRastor/fut21-web-app/raw/master/fut21-autobuyer.user.js

**Comment by oRastor** [comment]
> > fixed in new version
> 
> bro you still playing fut ?

no, just log in to make a fix...
