### ISSUE TITLE
EA changed Webapp coding.

### ISSUE THREAD

**Issue by ab-user1** [oRastor/fut21-web-app#62]
Hi dev,

EA has changed something in the Webapp coding that might makes the bot unsafe. I believe they spying more on botters now. If you want more info send me a pm. I got info from other bot dev who said it's unsafe to bot now and he will look into it tomorow. He thought he has fixed the issue last night but after careful check it wasn't.

**Comment by DonZlp** [comment]
> Hi dev,
> 
> EA has changed something in the Webapp coding that might makes the bot unsafe. I believe they spying more on botters now. If you want more info send me a pm. I got info from other bot dev who said it's unsafe to bot now and he will look into it tomorow. He thought he has fixed the issue last night but after careful check it wasn't.

Hi.  where shold I pm you? Is gitHub has private messaging feature?

**Comment by ab-user1** [comment]
> > Hi dev,
> > EA has changed something in the Webapp coding that might makes the bot unsafe. I believe they spying more on botters now. If you want more info send me a pm. I got info from other bot dev who said it's unsafe to bot now and he will look into it tomorow. He thought he has fixed the issue last night but after careful check it wasn't.
> 
> Hi. where shold I pm you? Is gitHub has private messaging feature?

I believe it's safe to use now but I'm not sure I don't use it.give me your mail
