### ISSUE TITLE
Problems with autobuyer on the latest Web App update on MacOs

### ISSUE THREAD

**Issue by Batita77** [oRastor/fut21-web-app#67]
<img width="2560" alt="Captura de ecrã 2021-03-17, às 18 04 58" src="https://user-images.githubusercontent.com/79223430/111518670-33220b00-874e-11eb-91ab-b50ecac9b6fa.png">

I have been using the autobuyer with zero problems but since the most recent Web App update my user name started to appear in the top left screen corner of the autobuyer menu and every time a player is bought appears a message from www.EA.com that says: "ASSERT: expected a scope of type object" that automatically stops the search.

Can someone help please?

Thanks

**Comment by oRastor** [comment]
It's like you are running two auto buyer scripts at the same time. Can you disable one with tampermonkey?

**Comment by KhairulAzmi21** [comment]
this has nothing to do with this autobuyer bro .

That message because ea staff enable dev tools on web app . that is what happen.
