### ISSUE TITLE
No longer showing up on Chrome

### ISSUE THREAD

**Issue by ackdogg** [oRastor/fut21-web-app#68]
Update came out today not sure if that has anything to do with it but when I have script enabled it still doesn't show on my Web App page. Hoping they haven't managed to stop it!

**Comment by Batita77** [comment]
I Have exactly the same problem, can someone help?

**Comment by oRastor** [comment]
New version:
https://github.com/oRastor/fut21-web-app/raw/master/fut21-autobuyer.user.js

**Comment by Batita77** [comment]
Allready working on my Chrome, thanks a lot for the help and quick updated version.

**Comment by ackdogg** [comment]
Thank you so much!
