### ISSUE TITLE
Consumables search

### ISSUE THREAD

**Issue by boefiee** [oRastor/fut21-web-app#8]
( Im using an alternate account with this autobuyer ) 
https://www.youtube.com/watch?v=Iz-YTOvR7yk

This is a position change filter: CDM -> CM very good filter. Last year i made at least 200K 400K a day with this filter and this autobuyer.
Now just look at the video, not 1 card popping up.
Try to search with the webapp or with the console and you will see LOADS AND LOADS of cards will pop up, the autobuyer simply unable to find these cards. 
This filter is just an example same goes with other filters like CAM --> CM, Chemistrystylecard HUNTER.

https://www.youtube.com/watch?v=CIWye9Zslmg 
When the autobuyer is searching normally it should say:

 [ time ] Received 0 items.
 [ time ] Received 0 items.
 [ time ] Received 0 items. 

etc.

First the autobuyer was searching normal but after a few minutes things changed and loads of buy fails came + the autobuyer tries to buy cards with the same ID ?!
Not even that, but [ time ] Received 0 items in the bottom screen also dissapears.
This all is proof that the autobuyer is just not working like it should be.

Dont get me wrong oRastor i am not critisizing you just trying to help you pointing the bugs and errors out so everybody can enjoy this program like last year.
Last year i had days where i easily made a miljon a day.
Even some rare days where good sbc's came out i had 2-3 miljon a day/evening, it was surreal.
I literally could make every team i want on the game, it was unbelievable.

Please acces the webapp yourself so you can see what i mean.

**Comment by vitorkrau** [comment]
He can't access the web app right now because his account market is locked. Could you provide him your secondary account so he can fix these bugs and add more features?

**Comment by RZR95** [comment]
yess i ahave same probllem this not normal 
maker need solutioon

**Comment by LaKo13** [comment]
Oh man - the raging fifa community is coming to Github. If you are experiencing mayor issues then please fix it yourself and stop being completely rude about it. 

Think it works half decently and happy to have changes made if the author finds time for it.

**Comment by BIFLE** [comment]
Created this account to say this : it's the best working app, simple to use and free. So please stop complaining and making rude request. Just ask politely :) 

Also I don't think posting youtube videos online, about this app, is a good idea.... the best way for EA or else to counter it so please stop that too :)

**Comment by boefiee** [comment]
> Created this account to say this : it's the best working app, simple to use and free. So please stop complaining and making rude request. Just ask politely :)
> 
> Also I don't think posting youtube videos online, about this app, is a good idea.... the best way for EA or else to counter it so please stop that too :)

You must be oRastor himself, just compare the autobuyer from last year with this year. I am not even using this thing anymore why ? because it is just not working.
Why would i leave this autobuyer aside if it was working great ? Like i said last year i made over a miljon easily a day.
If this autobuyer really worked i would be worlds richest fifa player, and i can prove that.
I also proved that the autobuyer is NOT working.
Now you come with proof yourself that the this is the best working app, its not even an app you dumb shit.
If this polish guy manage to fix this autobuyer like last year i will pay him for that but obviously h e cant.

**Comment by LaKo13** [comment]
Some pass this dude a tissue.

**Comment by oRastor** [comment]
@boefiee, its open-source solution was written for me last year. I created it just for me and put this code for other people. I don't use this application for this year. And fix player search for GitHub members, who make proper requests.

I closed your issue because you don't describe problem. Just wrote like "nothing works" as offtop messages like this:
https://github.com/oRastor/fut20-web-app/issues/2#issuecomment-537703129
https://github.com/oRastor/fut20-web-app/issues/2#issuecomment-538124401

But the problem was with the consumables search. And I use it only for player search as other users. Players search works fine, but you write comments like "nothing works, alarm!". So it's not a bug, its the feature.

You don't pay me a salary. But you allow yourself to write in such tone as you had already paid me millions, but I did not do the work. You allow yourself to write rude emails to me. Don’t talk about money here. It was not done for money and was not supported for the money.

> If this polish guy

I'm from Ukraine.

I have no desire to maintain this functionality after this.

**Comment by oRastor** [comment]
One more issue excellent description:
https://github.com/oRastor/fut20-web-app/issues/9#issue-503385720

**Comment by oRastor** [comment]
> yess i ahave same probllem this not normal i have share thiss programm many peopl all complaain me
> fukk this program maker need solutione pay money

Send me your PayPal account or Bitcoin and I will return all money that you have lost with not worked app.

**Comment by vitorkrau** [comment]
Rastor, please, I ask you to not bother with people like this guy and keep improving this autobuyer. I'd love to use it since is the only one open source. I'm busy with exams right now on my uni but I want to study writing tampermonkey scripts and maybe help you improve this app in the future. 

Thanks for everything and sorry about my english, it's not my main language.

**Comment by Mit010** [comment]
It actually does work. Are not getting like 200k-400k each day, but every coin is one earned easily and quicker then playing fifa games. Does it fail to buy some bargains ? YES. Is that because the autobuyer does not work? NO.
There are probably so many other types of paid autobuyers setup for autobuying these consumables and other easily sellable players,  and other players that are searching for it that you just can not get all bargains. 
I am very happy with this FREE script tho. As i made 200k+ so far with it. Thanks oRastor for every minute you have put into this.

**Comment by Verdagen** [comment]
I've earned over 2 million at the moment. Thank you for your time. Improve it when you have free time. Don't worry about negative comments, they just don't know how to use autobuyer.

PS- maybe open a donations, I will gladly send a donation in exchange for work.
Good luck man!

**Comment by boefiee** [comment]
> @boefiee, its open-source solution was written for me last year. I created it just for me and put this code for other people. I don't use this application for this year. And fix player search for GitHub members, who make proper requests.
> 
> I closed your issue because you don't describe problem. Just wrote like "nothing works" as offtop messages like this:
> [#2 (comment)](https://github.com/oRastor/fut20-web-app/issues/2#issuecomment-537703129)
> [#2 (comment)](https://github.com/oRastor/fut20-web-app/issues/2#issuecomment-538124401)
> 
> But the problem was with the consumables search. And I use it only for player search as other users. Players search works fine, but you write comments like "nothing works, alarm!". So it's not a bug, its the feature.
> 
> You don't pay me a salary. But you allow yourself to write in such tone as you had already paid me millions, but I did not do the work. You allow yourself to write rude emails to me. Don’t talk about money here. It was not done for money and was not supported for the money.
> 
> > If this polish guy
> 
> I'm from Ukraine.
> 
> I have no desire to maintain this functionality after this.

Why not use application for this year ?
Its a world of diffrence this year vs last year autobuyer, if someones deny that he is deluded.
Through new SBC's and filters i made miljons and miljons a week yet people who make 200K max a week 24/7 autobuyer tell me i dont know how to use lmao.
200K i make in a day on console without any problem people need autobuyer for this lol.
oRastor i will send you mails after this maybe you will understand more.
I am willing to help you where i can to to make this autobuyer the same as last year.

**Comment by TiebeVercoutter** [comment]
Maybe send an email to EA saying that they “fucked up” your autobuyer?

**Comment by mehrdadie** [comment]
Thanks a lot, oRastor, I really appreciate your time and efforts. I've earned a lot of coins with autobuyer without any problem and I'm looking forward to see new features and updates.

**Comment by boefiee** [comment]
When you try to make some coins with the autobuyer on the basis of SBC's that come out every day, its nearly impossible. Why ? because this year when you setup the autobuyer with a filter consisting of multiple players for example ( last week marquee matchup SBC came out, players instantly increase in price ) --> Gold --> Bundesliga--> Bayern,  the autobuyer will not find anything.
Last year i made miljons like this on the basis of SBC's where players who needed for those sbcs always increase in price i took advantage with that with autobuyer. But this year a filter consisting of multiple player the autobuyer just wont buy anything. Thats the major diffrence with last year. Autobuyer now only buys filters consisting of 1 player most of the times.

**Comment by Mit010** [comment]
> When you try to make some coins with the autobuyer on the basis of SBC's that come out every day, its nearly impossible. Why ? because this year when you setup the autobuyer with a filter consisting of multiple players for example ( last week marquee matchup SBC came out, players instantly increase in price ) --> Gold --> Bundesliga--> Bayern, the autobuyer will not find anything.
> Last year i made miljons like this on the basis of SBC's where players who needed for those sbcs always increase in price i took advantage with that with autobuyer. But this year a filter consisting of multiple player the autobuyer just wont buy anything. Thats the major diffrence with last year. Autobuyer now only buys filters consisting of 1 player most of the times.

In the last hour or so I made over 600-700k with the autobuyer so it actually does work.

**Comment by boefiee** [comment]
> > When you try to make some coins with the autobuyer on the basis of SBC's that come out every day, its nearly impossible. Why ? because this year when you setup the autobuyer with a filter consisting of multiple players for example ( last week marquee matchup SBC came out, players instantly increase in price ) --> Gold --> Bundesliga--> Bayern, the autobuyer will not find anything.
> > Last year i made miljons like this on the basis of SBC's where players who needed for those sbcs always increase in price i took advantage with that with autobuyer. But this year a filter consisting of multiple player the autobuyer just wont buy anything. Thats the major diffrence with last year. Autobuyer now only buys filters consisting of 1 player most of the times.
> 
> In the last hour or so I made over 600-700k with the autobuyer so it actually does work.

Sure...Can i contact you directly anywhere on sone email. Are you dutch by some chance ?

**Comment by AndyHeinz** [comment]
Hi,
Thanks for the Script. It kinda works for me too. I do have some verification issues,though. 
I tend to trigger verification after a couple of hundred requests. How many requests do you run per Minute? I also try to keep my result list above 0.
What's the best line here? Thanks!

**Comment by boefiee** [comment]
@AndyHeinz what works for you ? What filters you looking for and how do you set up the autobuyer ? I still have bugs. Due bot trying to buy the buy failed card multiple times IF it pops back up once in 5 minutes.
Also ok Mayer what filter or player the buyer just dont seem to pick up anything I am just honestly confused.
So many people claim here it's working perfectly fine yet the Dutch people who i shared the autobuyer with just like i shared it with them last year all experience the same stuff as me. The autobuyer just NOT buying anything. I even provided proof for it with the valuables I filled in. I feel like I m getting pranked so hard. People claim making coins but dont provide any proof..I proved the bot isn't working and I'm willing to help where I can and point everything out to let my friends enjoy this too who eagerly waiting for updates.

**Comment by oRastor** [comment]
https://github.com/oRastor/fut20-web-app/issues/2#issuecomment-536424115

Last year when I use this script for my own purpose, trade with one player.
Like Rashforrd or other popular and not very expensive player.
Its strategy worked well for me. And I think it must work fine this year too.

**Comment by boefiee** [comment]
Autobuyer keeps trying to buy the same thing which prevents it from buying what it should buy.

**Comment by vitorkrau** [comment]
I'm not having problems with the autobuyer trying to buy the same player. Did you update de script?

Also, I tried to buy chemistries styles today and it worked. Tried to reproduce the bug that you said it was happening and I couldn't.

**Comment by boefiee** [comment]
i downloaded the latest yes...i think youre not paying attention to the id's then.
obviously everybody has this problem that the autobuyer triest to buy a card which is already buy failed and it buy failes again.
also when its searching well you should see in bottom right screen received 0 times everytime and sometimes the top screen flips like crazy and then the bottom screen you dont see this received 0 items anymore and then after a few minutes it fixes itself or something and then it searches again..
very strange this year, al these trouble havent seen last year.

**Comment by vitorkrau** [comment]
That is strange. I don't have any of these problems and I kept it running for a couple of hours. Also, i was looking into the code and I saw that Rastor stores all auctions ids that the buyer tried to buy or bought just to stop this problem to occur.

**Comment by boefiee** [comment]
No mate the autobuyer still tries to buy buy failed cards, i can make a movie again if you and him dont believe me and I dont know how to code and stuf so rastor showed me what he did for nothing lol i just made an account here to tell that this autobuyer is not running like it should be believe me last year i let the autobuyer run literally 24 hours a day because i was actually making loads of money selling coins...NOW the autobuyer doesnt buy anything thats why i complain here and come with suggestions and i even point out what is wrong but this guy takes that as criticism and he doesnt actually wanna solve the problem...i wanted to help but obviously he doesnt give a shit or he just doesnt know how to code this program well and last year somebody else did it for him.

**Comment by LaKo13** [comment]
Didn't you mention before that you do not use this program anymore? Why are you still commenting on this? Let me use a metaphor, you are getting this free bicycle which you apparently do not use, however it seems that you rode it in the past at the tour de france but yet even though you do not use it anymore, you have a desperate urge to comment every distinct feature even though you know nothing about bicycle engineering. 

Have you thought about the fact that EA might be limiting purchases on the web app as 90% of programs are using this for automate trading activities? 

Above all, why do you keep bothering a guy about fixing the issues who has zero value add as he is not using it himself? Ever heard about the saying "beggars can't be choosers"? This would fit this topic precisely..

**Comment by boefiee** [comment]
> Didn't you mention before that you do not use this program anymore? Why are you still commenting on this? Let me use a metaphor, you are getting this free bicycle which you apparently do not use, however it seems that you rode it in the past at the tour de france but yet even though you do not use it anymore, you have a desperate urge to comment every distinct feature even though you know nothing about bicycle engineering.
> 
> Have you thought about the fact that EA might be limiting purchases on the web app as 90% of programs are using this for automate trading activities?
> 
> Above all, why do you keep bothering a guy about fixing the issues who has zero value add as he is not using it himself? Ever heard about the saying "beggars can't be choosers"? This would fit this topic precisely..

You have no idea how dumb you sound.
I told multiple times i am willing to pay money if this guy can fix this al because i need this.
EA did nothing.
Other autobuyer buy like crazy but i need this one.
Why dont you go and fuck your girl or boyfriend instead of big mouthing me ?

**Comment by oRastor** [comment]
5 minutes ago I tested consumables trading with my friend. It's works
https://www.youtube.com/watch?v=AEK9s1cYgPU

Any questions?

**Comment by LaKo13** [comment]
> You have no idea how dumb you sound.

The only one sounding extremely dumb and desperate is you.

**Comment by boefiee** [comment]
oRastor try consumables now then..
Come on, come online and try it right now.

[23:42:11] Received 0 items
[23:42:26] Received 0 items
[23:42:31] Received 0 items
[23:42:41] Received 0 items
[23:42:49] Received 0 items
[23:42:56] Received 0 items
[23:44:44] Received 0 items
[23:44:49] Received 0 items
[23:44:55] Received 0 items
[23:45:00] Received 0 items
[23:45:06] Received 0 items
[23:45:11] Received 0 items
[23:45:17] Received 0 items
[23:45:24] Received 0 items
[23:45:29] Received 0 items
[23:45:39] Received 0 items
[23:47:33] Received 0 items
[23:47:40] Received 0 items
[23:47:45] Received 0 items
[23:47:54] Received 0 items
[23:51:00] Received 0 items
[23:51:07] Received 0 items
[23:51:12] Received 0 items
[23:51:18] Received 0 items
[23:51:24] Received 0 items
[23:51:31] Received 0 items
[23:51:37] Received 0 items
[23:51:42] Received 0 items

Cam -> Cm max price and max buy now 1400 and sell 1900 wait time 1-3 max purchase 5.
Go on then come online and try it now.
This small penis community only big mouthing when they actually dont know how to code and only deliver trash.
Fix this piece of shit and i will pay you 250 euro.

**Comment by boefiee** [comment]
> > You have no idea how dumb you sound.
> 
> The only one sounding extremely dumb and desperate is you.

You are actually saying cards that popup on the PS4 are not popping up on the webapp and vice verca. You fucking dumb fuck stupid fucking fool go putt your head back up your ass you small dick dumb shit.
Go search the same shit you are searching on the autobuyer and you will see how many will pop up on ps4.
You must be the dumbest motherfucker of all these small dick idiots on here.

**Comment by boefiee** [comment]
:D hilarious :DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDd

**Comment by TiebeVercoutter** [comment]
Mate just go to sleep. If the developer doesn’t have time for this and doesn’t  need it himself why would he make it better for you. Go on a freelancer website and there you can pay someone 250€. Just stop crying like a baby here, I made about 500k with this autobuyer and that is perfectly fine with me. Don’t expect people here to make something for you so you could use it to make free money...

**Comment by boefiee** [comment]
Last year i couldnt thank him or whoever made this because i couldnt find him or her. Someone installed this for me on my pc.
Now that i found this guy i know for sure he did not develop the shit i used last year. I would love to meet the person who actually did that.
So thats why i tell him fix this shit and ill give you some money as a thanks.

**Comment by boefiee** [comment]
Look at this shit, great piece of engineering.
All of you dumb fucks shouldnt talk.
Or you all 1 and the same person making 100 accounts and react on 1 topic like a fucking no lifer.

**Comment by LaKo13** [comment]
The cringe is getting real on here. @oRastor, do yourself a favour and delete this repository.

**Comment by Mit010** [comment]
@boefiee : the filters you told: 1400 buy CAM -> CM
[01:46:27]  -- Selling for: 3800
[01:47:16] --- --- [258785350215] 1400 buyed
[01:47:16]  -- Selling for: 1900
[01:47:34] --- --- [258785338874] 1100 buyed
[01:47:34]  -- Selling for: 1900
[01:47:34] --- --- [258785310750] 1400 buy failed
[01:47:39] --- --- [258785351100] 1100 buyed
[01:47:39]  -- Selling for: 1900
[01:47:42] --- --- [258785357137] 450 buyed
[01:47:42]  -- Selling for: 1900
[01:47:42] --- --- [258785378892] 1400 buy failed
[01:47:54] --- --- [258785348779] 1400 buyed
[01:47:54]  -- Selling for: 1900
[01:48:01] --- --- [258785379731] 1400 buyed
[01:48:01]  -- Selling for: 1900

[01:47:16] Received 1 items
[01:47:16] --- --- [258785350215] [59 Minutes] 1400
[01:47:22] Received 0 items
[01:47:28] Received 0 items
[01:47:29] Received 0 items
[01:47:32] Received 0 items
[01:47:34] Received 3 items
[01:47:34] --- --- [258785338874] [59 Minutes] 1100
[01:47:34] --- --- [258785310750] [1 Hour] 1400
[01:47:34] --- --- [258785323178] [1 Hour] 1400
[01:47:39] Received 1 items
[01:47:39] --- --- [258785351100] [59 Minutes] 1100
[01:47:42] Received 3 items
[01:47:42] --- --- [258785357137] [1 Hour] 450
[01:47:42] --- --- [258785338874] [59 Minutes] 1100
[01:47:42] --- --- [258785378892] [59 Minutes] 1400
[01:47:45] Received 0 items
[01:47:49] Received 3 items
[01:47:49] --- --- [258785357137] [59 Minutes] 450
[01:47:49] --- --- [258785338874] [59 Minutes] 1100
[01:47:49] --- --- [258785378892] [59 Minutes] 1400
[01:47:51] Received 0 items
[01:47:53] Received 1 items
[01:47:53] --- --- [258785348779] [59 Minutes] 1400
[01:47:56] Received 0 items
[01:48:01] Received 4 items
[01:48:01] --- --- [258785357137] [59 Minutes] 450
[01:48:01] --- --- [258785338874] [59 Minutes] 1100
[01:48:01] --- --- [258785378892] [59 Minutes] 1400
[01:48:01] --- --- [258785379731] [59 Minutes] 1400
[01:48:03] Received 0 items
[01:48:05] Received 0 items
[01:48:08] Received 0 items
[01:48:15] Received 0 items
[01:48:21] Received 0 items

Like in 2 minutes I get multiple buys :)

**Comment by boefiee** [comment]
> @boefiee : the filters you told: 1400 buy CAM -> CM
> [01:47:16] --- --- [258785350215] 1400 buyed
> [01:47:16] -- Selling for: 1900
> [01:47:34] --- --- [258785338874] 1100 buyed
> [01:47:34] -- Selling for: 1900
> [01:47:34] --- --- [258785310750] 1400 buy failed
> [01:47:39] --- --- [258785351100] 1100 buyed
> [01:47:39] -- Selling for: 1900
> [01:47:42] --- --- [258785357137] 450 buyed
> [01:47:42] -- Selling for: 1900
> [01:47:42] --- --- [258785378892] 1400 buy failed
> [01:47:54] --- --- [258785348779] 1400 buyed
> [01:47:54] -- Selling for: 1900
> [01:48:01] --- --- [258785379731] 1400 buyed
> [01:48:01] -- Selling for: 1900
> 
> [01:47:16] Received 1 items
> [01:47:16] --- --- [258785350215] [59 Minutes] 1400
> [01:47:22] Received 0 items
> [01:47:28] Received 0 items
> [01:47:29] Received 0 items
> [01:47:32] Received 0 items
> [01:47:34] Received 3 items
> [01:47:34] --- --- [258785338874] [59 Minutes] 1100
> [01:47:34] --- --- [258785310750] [1 Hour] 1400
> [01:47:34] --- --- [258785323178] [1 Hour] 1400
> [01:47:39] Received 1 items
> [01:47:39] --- --- [258785351100] [59 Minutes] 1100
> [01:47:42] Received 3 items
> [01:47:42] --- --- [258785357137] [1 Hour] 450
> [01:47:42] --- --- [258785338874] [59 Minutes] 1100
> [01:47:42] --- --- [258785378892] [59 Minutes] 1400
> [01:47:45] Received 0 items
> [01:47:49] Received 3 items
> [01:47:49] --- --- [258785357137] [59 Minutes] 450
> [01:47:49] --- --- [258785338874] [59 Minutes] 1100
> [01:47:49] --- --- [258785378892] [59 Minutes] 1400
> [01:47:51] Received 0 items
> [01:47:53] Received 1 items
> [01:47:53] --- --- [258785348779] [59 Minutes] 1400
> [01:47:56] Received 0 items
> [01:48:01] Received 4 items
> [01:48:01] --- --- [258785357137] [59 Minutes] 450
> [01:48:01] --- --- [258785338874] [59 Minutes] 1100
> [01:48:01] --- --- [258785378892] [59 Minutes] 1400
> [01:48:01] --- --- [258785379731] [59 Minutes] 1400
> [01:48:03] Received 0 items
> [01:48:05] Received 0 items
> [01:48:08] Received 0 items
> [01:48:15] Received 0 items
> [01:48:21] Received 0 items
> 
> Like in 2 minutes I get multiple buys :)

LOL 2 minutes few buys after that the autobuyer goes fucking crazy like i see what you paste and then 20 mintes nothing, like i said you dumb shit go on your console and multiple will pop up every minute you fucking braindead.
When the autobuyer is searching normal you should have received 0 items ANYTIME. the fact that it goes crazy shows its not well coded.
You obviously didnt experienced last years autobuyer, it never gone this crazy.
Dumb idiots like you happy with few K and then big mouthing here that it works like it works like shit.
People like you are not even worth argueing you dont even know how this autobuyer works and should work. dumb shit.

**Comment by boefiee** [comment]
Wow you made a few K in 2 mins, and then 20/30 you dont make shit lmfao.
Last year it was stable, i had moments i made 10K every minute.
Dumb fucks typing shit here dont know anything.
This polak kurwo just stole the idea of the actual goat and poorly coded it himself so obvious.

**Comment by Mit010** [comment]
I made over 2 million in the last days with the Juve / Liverpool SBC with this autobuyer. This autobuyer works. YOU do not know how to handle it. There are a few things you need to do to make it work even bettter, but this is due to the EA side and not the autobuyer. oRastor just ban this clown.

**Comment by boefiee** [comment]
> I made over 2 million in the last days with the Juve / Liverpool SBC with this autobuyer, on just one account. My friend also made a millie. This autobuyer works. YOU do not know how to handle it. There are a few things you need to do to make it work even bettter, but this is due to the EA side and not the autobuyer. oRastor just ban this clown.

Je praat alleen maar onzin kerel, dat weet je dondersgoed.
Ik heb meer gemaakt op de console aan de hand van die sbc's dan met de autobuyer zelf.
Als je mn filmpjes bekijkt dan zie je dat ik niks verkeerds doe en netzoals jou alles goed invult.
Jij moet blij wezen dat je uberhaupt nu deze autobuyer gebruikt waar je zogenaamd heel veel aan hebt, want degene die je daar dankbaar voor moet wezen ben ik.
Ik heb deze autobuyer vorig jaar verspreid onder de Nederlanders.
Laat jij nou maar eens een keer bewijs zien hoeveel jij nou wel niet heb gemaakt en leg mij dan maar eens haarfijn uit wat ik verkeerd doe, kanker sukkel die je bent.
Dat kan je namelijk niet :D

**Comment by Mit010** [comment]
Jij hebt deze van marktplaats gekocht kneusje Dani ;)

**Comment by boefiee** [comment]
Ik heb dit van hem overgenomen inderdaad, net zoals jij dit waarschijnlijk van mensen heb overgekocht.
Geen onzin gaan praten maat, gewoon laten zien dat jij 2 miljoen maakt met een kapot programmatje.
Als jij net zoveel heb gemaakt als dat ik vorig jaar heb gemaakt mag je komen praten, honderden miljoenen, elke coin verkocht :)

**Comment by boefiee** [comment]
Ik wacht nog steeds, pussy.

**Comment by Mit010** [comment]
I don't have to show you anything. Why would I. Just go hate your life because you can not snipe and need to pay money for other autobuyers to do the trick for you, when it's all working for us :)!

**Comment by boefiee** [comment]
Mensen oplichten op marktplaats is waar je goed in bent M.Lutz
Vorig zijn er heel veel mensen boos op jou geweest hhh.

**Comment by Mit010** [comment]
![futt coinsssssss](https://user-images.githubusercontent.com/33159826/66691783-1cde6880-ec99-11e9-8727-bdeb8c78fb95.png)

**Comment by boefiee** [comment]
You scammed people last year ''selling'' this autobuyer on dutch ebay website called marktplaats.
Still loads of people mad at you, and i can promise you they will continue to look for you as i have heard lately.
I actually made hundreds of miljons last year with this same autobuyer and i sold every coin you dumb fuck.
Now again, show evidence of you making 2 miljon ( IN THE LAST DAYS WITH THE AUTOBUYER).
You cant.
If there is one know what to snipe and what filters to look for its me.
Now go watch lion king you poor little scamming kid.

**Comment by Mit010** [comment]
I dont think you are a sane person. You lost your mind LOL

**Comment by boefiee** [comment]
> I made over 2 million in the last days with the Juve / Liverpool SBC with this autobuyer, on just one account. My friend also made a millie. This autobuyer works. YOU do not know how to handle it. There are a few things you need to do to make it work even bettter, but this is due to the EA side and not the autobuyer. oRastor just ban this clown.

''There are a few things you need to do to make it work even bettter, but this is due to the EA side and not the autobuyer''

Go on then, share it here so everyone could actually benefit from your genious work...
You cant because your a small dick 18 year old kid.

**Comment by Mit010** [comment]
I am 15 :D:D:DD and make millions with this autobuyer and you cant make 100k :D:D

**Comment by boefiee** [comment]
Wow 2 million in 16 days....LMFAO.

**Comment by KhairulAzmi21** [comment]
Hi @Mit010 , mind sharing tips how your use this autobuyer ? this autobuyer works for me .but for me, even 10k per day is so hard .

**Comment by Mitchell46** [comment]
I'm seeing the same problems as @boefiee. I was searching for 10 minutes CAM>CM and didn't found anything. But I also noticed that EA updates the SBC so it's much harder to have big profits from SBC's. It's not working like last year but I think it's a combination of the script and EA making it harder for us. Yersterdag I spend 2 hours of searching and made 100k profit. last friday with the Scream cards I made 200K in a half hour. I think is the best idea to search when special cards are released. 
And for safety I stop searching every 5 minutes en go to my transferlist so I can check if there is a puzzle.

@boefiee ik ben ook Nederlands

**Comment by Mitchell46** [comment]
Moreover don't get me wrong.. I'm still very happy with the autobuyer. I only use it for getting a better team. It's impossible to do that just playing Fut20 on a console. On other pages I see more people earn max 100k a day on a ordinary day.

**Comment by KhairulAzmi21** [comment]
> I'm seeing the same problems as @boefiee. I was searching for 10 minutes CAM>CM and didn't found anything. But I also noticed that EA updates the SBC so it's much harder to have big profits from SBC's. It's not working like last year but I think it's a combination of the script and EA making it harder for us. Yersterdag I spend 2 hours of searching and made 100k profit. last friday with the Scream cards I made 200K in a half hour. I think is the best idea to search when special cards are released.
> And for safety I stop searching every 5 minutes en go to my transferlist so I can check if there is a puzzle.
> 
> @boefiee ik ben ook Nederlands
> 
> edit: 5 hours later I made 10K profit today. Cant find anything the last hours.

Can you share me some tips how to utilize this autobuyer ? its working for me . but sometimes I cannot get profit.
